version: '2.2'
services:
  postgres:
    restart: always
    image: postgres:11.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisnotprod
      - POSTGRES_DB=eastwood
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-net
  app:
    image: eastwood:latest
    scale: 1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eastwood
      - POSTGRES_HOST=postgres
    volumes:
        - ".:/src/"
    networks:
      - pg-net
    links:
      - postgres 
    depends_on:
      - postgres
networks:
  pg-net:
